### ISSUE TITLE
Split "RDO Community Day" @ FOSDEM into separate `.yml` file?

### ISSUE THREAD

**Issue by garrett** [OSAS/rh-events#155]
As RDO Community Day takes place in a different place at a different time, I would suggest moving it to a different file. It's not a talk that's part of FOSDEM, even if it is taking place somewhat near FOSDEM in space-time.

From https://github.com/OSAS/rh-events/blob/f6789e6ce4168a78f73f1d7a2dc167ddb84ec076/2016/FOSDEM.yml#L25-L32:

```yaml
- title: RDO Community Day
  location: IBM Client Center, Brussels, Belgium
  start: 2016-01-29 08:00 CET
  end: 2016-01-29 18:00 CET
  description: |
    RDO Community Day at the CentOS Dojo. Schedule and details at
    http://rdoproject.org/events/rdo-day-fosdem-2016
    Register at https://www.eventbrite.co.uk/e/centos-dojo-brussels-belgium-jan-29th-2016-tickets-19589843750
```
